### PR TITLE
remove blue line, compact spacing

### PR DESCRIPTION
**Pull request by srambach**
I got rid of the blue line, and managed to get the compact spacing working pretty well. Just a warning - I didn't have time to make sure everything is cleaned up well but wanted to get this to you before leaving.
A few notes:
- I added CSS on the DataListComponent to get rid of the blue line.
- I added a <DataList> on the inner data list so that it could be marked as pf-m-compact
- I removed the external link icon. It is not needed (Liz agrees) and its a tag was causing extra space below for some reason.

I'll add a screen shot below for what it should turn out as.
@AjayJagan @cristianonicolai

image

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@srambach looks really nice! :)

**Comment by AjayJagan** [comment]
> I got rid of the blue line, and managed to get the compact spacing working pretty well. Just a warning - I didn't have time to make sure everything is cleaned up well but wanted to get this to you before leaving.
> A few notes:
> 
> * I added CSS on the DataListComponent to get rid of the blue line.
> * I added a  on the inner data list so that it could be marked as pf-m-compact
> * I removed the external link icon. It is not needed (Liz agrees) and its a tag was causing extra space below for some reason.
> 
> I'll add a screen shot below for what it should turn out as.
> @AjayJagan @cristianonicolai
> 
> image

@cristianonicolai - is the external link icon not required? I guess we are linking the endpoint to the icon .

**Comment by srambach** [comment]
I didn't realize that was a different link - that must be what the external link icon was going to in Liz's mockups - she couldn't remember for sure what it was. Is there a separate name/text for that? Typically the external link icon would go along with a text link to indicate that it will take you out of your current context. Having it next to an internal navigational link but going to a different place would be confusing.
@cristianonicolai @ajayjagan

**Comment by srambach** [comment]
I added the second external link back - but I didn't know what the text would be.
Also, the bold is probably debatable :) 
@AjayJagan @cristianonicolai 
image

**Pull request closed without merging**
